name: Heroku Deployment

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to Heroku
        uses: ElayGelbart/Heroku-Auto-Deployment@v1.0.6
        with:
          herokuApiKey: ${{secrets.HEROKU_API_KEY}}
          herokuAppName: ${{secrets.HEROKU_APP_NAME}}
